version: '3'
services:
  zap:
    image: owasp/zap2docker-stable
    container_name: zap
    tty: true
    networks:
      - scan_net

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - scan_net

networks:
  scan_net:

