version: '3'
services:
  zap:
    image: owasp/zap2docker-stable
    container_name: zap
    networks:
      - scan_net
    entrypoint: [""]
    volumes:
      - ./zap-scanner:/zap/wrk/:rw

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "9090:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - scan_net

networks:
  scan_net:

