version: '3'
services:
  zap:
    image: owasp/zap2docker-weekly
    container_name: zap
    networks:
      - scan_net
    ports:
      - "8090:8090"
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "9090:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - scan_net

networks:
  scan_net:

